{{ if .Values.fluentd.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bitbucket.fullname" . }}-fluentd-config
  labels:
  {{- include "bitbucket.labels" . | nindent 4 }}
data:
  fluent.conf: |


    <source>
      @type forward
      port 24224
      bind 0.0.0.0
    </source>

    <filter **>
      @type record_transformer
      <record>
        podname "#{ENV['POD_NAME']}"
        podnamespace "#{ENV['POD_NAMESPACE']}"
        podip "#{ENV['POD_IP']}"
        helmrelease "#{ENV['HELM_RELEASE_NAME']}"
      </record>
    </filter>

    <filter **>
      @type stdout
    </filter>

    <match **>
      @type elasticsearch
      host {{ .Values.fluentd.elasticsearch.hostname }}
      logstash_format true
    </match>
{{ end }}